ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER magazzino IDENTIFIED BY magazzino_pwd;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO magazzino;
ALTER USER magazzino ACCOUNT UNLOCK;
ALTER USER magazzino QUOTA UNLIMITED ON USERS;
