CREATE TABLE UTENTI (
                        ID NUMBER PRIMARY KEY,
                        USERNAME VARCHAR2(50) NOT NULL UNIQUE,
                        PASSWORD VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE UTENTI_SEQ START WITH 1 INCREMENT BY 1;