-- Sequence per Prodotto
CREATE SEQUENCE magazzino.SEQ_PRODOTTO START WITH 1 INCREMENT BY 1;

-- Tabella Prodotto
CREATE TABLE magazzino.PRODOTTO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DESCRIZIONE VARCHAR2(255),
    PREZZO NUMBER(10,2) NOT NULL
);

-- Sequence per Magazzino
CREATE SEQUENCE magazzino.SEQ_MAGAZZINO START WITH 1 INCREMENT BY 1;

-- Tabella Magazzino
CREATE TABLE magazzino.MAGAZZINO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    INDIRIZZO VARCHAR2(255),
    CAPACITA NUMBER(10) NOT NULL
);

-- Sequence per Fattura
CREATE SEQUENCE magazzino.SEQ_FATTURA START WITH 1 INCREMENT BY 1;

-- Tabella Fattura
CREATE TABLE magazzino.FATTURA (
    ID NUMBER PRIMARY KEY,
    DATA_FATTURA DATE NOT NULL,
    IMPORTO NUMBER(10,2) NOT NULL,
    ID_PRODOTTO NUMBER NOT NULL,
    CONSTRAINT FK_FATTURA_PRODOTTO FOREIGN KEY (ID_PRODOTTO) REFERENCES magazzino.PRODOTTO(ID)
);

-- Tabella di relazione molti-a-molti tra Prodotto e Magazzino
CREATE TABLE magazzino.PRODOTTO_MAGAZZINO (
    ID NUMBER PRIMARY KEY,
    ID_PRODOTTO NUMBER NOT NULL,
    ID_MAGAZZINO NUMBER NOT NULL,
    QUANTITA NUMBER(10) DEFAULT 0,
    CONSTRAINT FK_PRODMAG_PRODOTTO FOREIGN KEY (ID_PRODOTTO) REFERENCES magazzino.PRODOTTO(ID),
    CONSTRAINT FK_PRODMAG_MAGAZZINO FOREIGN KEY (ID_MAGAZZINO) REFERENCES magazzino.MAGAZZINO(ID),
    CONSTRAINT UQ_PRODMAG UNIQUE (ID_PRODOTTO, ID_MAGAZZINO)
);
