-- Inserimento dati di esempio per PRODOTTO
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Pasta Barilla', 'Pasta di semola di grano duro 500g', 1.29);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Latte Parmalat', 'Latte intero UHT 1L', 1.09);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Olio Extra Vergine', 'Olio extravergine di oliva 1L', 5.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Biscotti Mulino Bianco', 'Biscotti frollini 350g', 2.39);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Acqua Sant’Anna', 'Acqua naturale 1.5L', 0.35);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Caffè Lavazza', 'Caffè macinato 250g', 3.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Detersivo Dash', 'Detersivo liquido per lavatrice 1.2L', 4.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Tonno Rio Mare', 'Tonno all’olio di oliva 3x80g', 4.29);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Mozzarella Galbani', 'Mozzarella fresca 125g', 1.19);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Succhi Yoga', 'Succo di frutta assortito 200ml', 0.89);

-- Inserimento dati di esempio per MAGAZZINO (se non già presenti)
INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA) VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Nord', 'Via Milano 10, Torino', 1000);
INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA) VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Centro', 'Via Roma 22, Bologna', 800);
INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA) VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Sud', 'Via Napoli 5, Bari', 600);

-- Inserimento dati di esempio per PRODOTTO_MAGAZZINO (relazioni e quantità)
-- Assumendo che gli ID partano da 1 in ordine di inserimento
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (1, 1, 1, 200);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (2, 1, 2, 150);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (3, 2, 1, 100);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (4, 2, 3, 80);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (5, 3, 2, 60);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (6, 4, 1, 120);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (7, 5, 3, 300);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (8, 6, 2, 90);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (9, 7, 1, 50);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (10, 8, 2, 70);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (11, 9, 3, 110);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (12, 10, 1, 40);

-- Inserimento dati di esempio per FATTURA (5 fatture riferite a prodotti esistenti)
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-10', 'YYYY-MM-DD'), 12.90, 1); -- Pasta Barilla
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-11', 'YYYY-MM-DD'), 10.90, 2); -- Latte Parmalat
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-12', 'YYYY-MM-DD'), 54.90, 3); -- Olio Extra Vergine
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-13', 'YYYY-MM-DD'), 23.90, 4); -- Biscotti Mulino Bianco
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-13', 'YYYY-MM-DD'), 3.50, 5); -- Acqua Sant’Anna
