PRODOTTI

INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Riso Scotti', 'Riso Arborio 1kg', 2.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Farina 00 Caputo', 'Farina 00 per pizza 1kg', 1.39);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Zucchero Eridania', 'Zucchero bianco 1kg', 1.19);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Sale Iodato', 'Sale alimentare iodato 1kg', 0.59);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Cornflakes Kelloggs', 'Cereali per colazione 375g', 3.19);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Miele Millefiori', 'Miele italiano 500g', 4.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Cioccolato Lindt', 'Tavoletta fondente 70% 100g', 2.29);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Yogurt Danone', 'Yogurt bianco 2x125g', 1.09);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Burro Lurpak', 'Burro di centrifuga 250g', 2.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Grana Padano', 'Formaggio DOP grattugiato 200g', 4.59);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Prosciutto Cotto Alta Qualità', 'Prosciutto cotto affettato 120g', 2.79);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Speck Alto Adige', 'Speck affettato 100g', 3.29);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Salmone Affumicato', 'Salmone norvegese 100g', 4.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Pane Integrale', 'Pane integrale confezionato 500g', 1.69);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Fette Biscottate', 'Fette biscottate classiche 315g', 1.39);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Passata Mutti', 'Passata di pomodoro 700g', 1.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Maionese Calvè', 'Maionese classica 250ml', 1.89);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Ketchup Heinz', 'Ketchup classico 400ml', 2.59);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Aceto Balsamico di Modena', 'IGP 250ml', 2.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Pomodori Pelati', 'Pomodori pelati in lattina 400g', 0.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Fagioli Borlotti', 'Fagioli in scatola 400g', 0.89);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Piselli Finissimi', 'Piselli in lattina 400g', 0.95);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Spinaci Surgelati', 'Cubetti di spinaci 600g', 1.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Patate Fritte', 'Bastoncini surgelati 1kg', 2.39);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Coca-Cola', 'Bibita gassata 1.5L', 1.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Birra Peroni', 'Birra lager 66cl', 1.19);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Detersivo Piatti', 'Detersivo limone 750ml', 1.79);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Candeggina Ace', 'Candeggina classica 1L', 1.29);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Ammorbidente Lenor', 'Ammorbidente concentrato 750ml', 2.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Sgrassatore Chanteclair', 'Sgrassatore universale 625ml', 2.39);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Shampoo Garnier', 'Shampoo rinforzante 250ml', 2.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Dentifricio Colgate', 'Dentifricio protezione carie 75ml', 1.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Sapone Liquido', 'Sapone mani antibatterico 300ml', 1.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Carta Igienica', 'Carta igienica 4 rotoli', 2.49);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Pannolini Pampers', 'Pannolini Progressi taglia 3 20pz', 7.99);
INSERT INTO magazzino.PRODOTTO (ID, NOME, DESCRIZIONE, PREZZO) VALUES (magazzino.SEQ_PRODOTTO.NEXTVAL, 'Crocchette per Gatti', 'Alimento secco pollo 1.5kg', 4.49);






PRODOTTO-MAGAZZINO



INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (11, 11, 1, 50);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (12, 12, 1, 100);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (13, 13, 1, 80);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (14, 14, 1, 200);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (15, 15, 1, 30);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (16, 16, 1, 15);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (17, 17, 1, 60);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (18, 18, 1, 45);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (19, 19, 1, 25);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (20, 20, 1, 40);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (21, 21, 1, 35);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (22, 22, 1, 35);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (23, 23, 1, 20);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (24, 24, 1, 55);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (25, 25, 1, 70);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (26, 26, 1, 120);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (27, 27, 1, 40);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (28, 28, 1, 40);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (29, 29, 1, 25);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (30, 30, 1, 90);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (31, 31, 1, 85);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (32, 32, 1, 85);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (33, 33, 1, 40);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (34, 34, 1, 50);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (35, 35, 1, 150);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (36, 36, 1, 120);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (37, 37, 1, 60);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (38, 38, 1, 40);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (39, 39, 1, 45);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (40, 40, 1, 55);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (41, 41, 1, 30);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (42, 42, 1, 40);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (43, 43, 1, 25);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (44, 44, 1, 100);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (45, 45, 1, 20);
INSERT INTO magazzino.PRODOTTO_MAGAZZINO (ID, ID_PRODOTTO, ID_MAGAZZINO, QUANTITA) VALUES (46, 46, 1, 15);




MAGAZZINO


INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA)
VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Sud', 'Via Roma 50, Napoli', 1500);

INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA)
VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Centro', 'Via Emilia 22, Bologna', 1200);

INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA)
VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Est', 'Viale Venezia 5, Padova', 800);

INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA)
VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Ovest', 'Corso Francia 100, Bardonecchia', 900);

INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA)
VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Adriatico', 'Via Adriatica 1, Ancona', 1100);

INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA)
VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Tirreno', 'Piazza Dante 12, Genova', 1300);

INSERT INTO magazzino.MAGAZZINO (ID, NOME, INDIRIZZO, CAPACITA)
VALUES (magazzino.SEQ_MAGAZZINO.NEXTVAL, 'Magazzino Isole', 'Via Garibaldi 3, Palermo', 3000);





 FATTURE




INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-10', 'YYYY-MM-DD'), 12.90, 1); -- Pasta Barilla
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-11', 'YYYY-MM-DD'), 10.90, 2); -- Latte Parmalat
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-12', 'YYYY-MM-DD'), 54.90, 3); -- Olio Extra Vergine
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-13', 'YYYY-MM-DD'), 23.90, 4); -- Biscotti Mulino Bianco
INSERT INTO magazzino.FATTURA (ID, DATA_FATTURA, IMPORTO, ID_PRODOTTO) VALUES (magazzino.SEQ_FATTURA.NEXTVAL, TO_DATE('2026-01-13', 'YYYY-MM-DD'), 3.50, 5); -- Acqua Sant’Anna








































