
# APPLICATION
spring.application.name=magazzino

#  ORACLE DATASOURCE

spring.datasource.url=jdbc:oracle:thin:@//oracle-service:1521/XE?oracle.jdbc.timezoneAsRegion=true&sessionTimeZone=Europe/Rome
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:magazzino}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:magazzino_pdw}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


#  SCHEDULER FATTURE

# true = attivo   /   false = disattivo
fatture.check.enabled=true

# Esecuzione ogni giorno alle 01:00 /per ogni minuto    - 0 0 1 * * * - 0 */10 * * * *(10 min)
fatture.check.cron=0 */10 * * * *

# Log del scheduling
logging.level.org.springframework.scheduling=DEBUG

#  SCHEDULER INVENTARIO

# true = attivo   /   false = disattivo
jobs.inventory.enabled=true

# Ogni 5 minuti (300000 ms)
inventory.check.rate=300000

# Soglia minima fallback
inventory.min.threshold=5

# TIMEZONE APPLICAZIONE & JSON

spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Rome
spring.jackson.time-zone=Europe/Rome

# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update

# CONFIGURATION UTENTE

fatture.default-username=system