spring.application.name=magazzino

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@host.docker.internal:1521/XE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:magazzino}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:magazzino_pwd}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

cart.reservation.minutes=20
