spring.application.name=magazzino
spring.datasource.url=jdbc:oracle:thin:@oracle-service:1521/XEspring.datasource.username=${SPRING_DATASOURCE_USERNAME:magazzino}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:magazzino_pdw}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
inventory.check.rate=300000          # Ogni 5 min (millisecondi)
inventory.min.threshold=5            # Soglia minima globale fallback



