
-- SCHEMA LOGICO COMPLETO CON CHIAVI PRIMARIE E CHIAVI ESTERNE

CREATE TABLE PRODOTTO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRIZIONE VARCHAR(255),
    PREZZO DECIMAL(10,2) NOT NULL
);

CREATE TABLE MAGAZZINO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    INDIRIZZO VARCHAR(255),
    CAPACITA INT NOT NULL,
    STOCK_STATUS VARCHAR(30)
);

CREATE TABLE PRODOTTO_MAGAZZINO (
    ID INT PRIMARY KEY,
    ID_PRODOTTO INT NOT NULL,
    ID_MAGAZZINO INT NOT NULL,
    QUANTITA INT NOT NULL,
    STATUS VARCHAR(30),
    SCORTA_MIN INT NOT NULL,
    FOREIGN KEY (ID_PRODOTTO) REFERENCES PRODOTTO(ID),
    FOREIGN KEY (ID_MAGAZZINO) REFERENCES MAGAZZINO(ID)
);

CREATE TABLE FATTURA (
    ID INT PRIMARY KEY,
    DATA_FATTURA DATE NOT NULL,
    IMPORTO DECIMAL(10,2) NOT NULL,
    ID_PRODOTTO INT NOT NULL,
    NUMERO VARCHAR(50),
    QUANTITA INT NOT NULL,
    FOREIGN KEY (ID_PRODOTTO) REFERENCES PRODOTTO(ID)
);

CREATE TABLE TEMPO (
    ID INT PRIMARY KEY,
    DATA TIMESTAMP NOT NULL,
    ANNO INT,
    MESE INT,
    MESE_NOME VARCHAR(20),
    GIORNO INT,
    SETTIMANA INT,
    QUARTER VARCHAR(3),
    ORA INT,
    MINUTO INT,
    SECONDO INT
);

CREATE TABLE JOB_EXECUTION (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(30) NOT NULL,
    ERROR_TYPE VARCHAR(30),
    ERROR_MESSAGE VARCHAR(500),
    ID_TEMPO_START INT NOT NULL,
    ID_TEMPO_END INT,
    FOREIGN KEY (ID_TEMPO_START) REFERENCES TEMPO(ID),
    FOREIGN KEY (ID_TEMPO_END) REFERENCES TEMPO(ID)
);
